### ISSUE TITLE
only works in Firefox Nightly

### ISSUE THREAD

**Issue by jorendorff** [mrrrgn/glowing-guacamole#6]
options:

* rip out the ES6 stuff that isn't universally supported
* hook up Babel
* put a "best viewed in Firefox Nightly" banner on it

**Comment by fitzgen** [comment]
Fwiw, dev edition wfm too.

**Comment by kmaglione** [comment]
Damn straight. https://bugzil.la/932517 landed in 44, and `let` and `const` are supported in release branches of Chrome.
